substitutions:
  name: ble-proxy-cuarto-maria
  friendly_name: "BLE Proxy Cuarto María"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "ESP32-S3 Bluetooth Proxy for Bermuda (Room: Cuarto María)"
  project:
    name: manuel.bermuda_ble_proxy
    version: "1.2.3"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

logger:
  baud_rate: 0

api:
  encryption:
    key: "SSQuJ8uB0VwYRgALCrODOO3prKtCoff9FwFDulpHSKQ="

ota:
  - platform: esphome

wifi:
  ssid: "Pom IoT"
  password: "Francis163069*"
  fast_connect: true
  power_save_mode: none
  output_power: 17.5dB
  reboot_timeout: 0s
  # manual_ip:
  #   static_ip: 192.168.10.238
  #   gateway: 192.168.10.1
  #   subnet: 255.255.255.0
  #   dns1: 192.168.10.1
  ap:
    ssid: "BLE-Proxy-Maria Fallback"
    password: "Setup1234"

captive_portal:

web_server:
  port: 80

bluetooth_proxy:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"

button:
  - platform: restart
    name: "${friendly_name} Restart"

status_led:
  pin: GPIO48